# Generated by Django 4.2.1 on 2025-03-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("go", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consorcium",
            name="slug",
            field=models.SlugField(
                blank=True, default="", max_length=30, verbose_name="URL_cons"
            ),
        ),
        migrations.AddField(
            model_name="genes",
            name="slug",
            field=models.SlugField(
                blank=True, default="", max_length=30, verbose_name="URL_gene"
            ),
        ),
        migrations.AddField(
            model_name="phenotype",
            name="slug",
            field=models.SlugField(
                blank=True, default="", max_length=30, verbose_name="URL_pheno"
            ),
        ),
        migrations.AddField(
            model_name="rs",
            name="slug",
            field=models.SlugField(
                blank=True, default="", max_length=30, verbose_name="URL_rs"
            ),
        ),
    ]
