# Generated by Django 4.2.1 on 2025-03-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("go", "0002_consorcium_slug_genes_slug_phenotype_slug_rs_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consorcium",
            name="slug",
            field=models.SlugField(max_length=30, unique=True, verbose_name="URL_cons"),
        ),
        migrations.AlterField(
            model_name="genes",
            name="slug",
            field=models.SlugField(max_length=30, unique=True, verbose_name="URL_gene"),
        ),
        migrations.AlterField(
            model_name="phenotype",
            name="slug",
            field=models.SlugField(
                max_length=30, unique=True, verbose_name="URL_pheno"
            ),
        ),
        migrations.AlterField(
            model_name="rs",
            name="slug",
            field=models.SlugField(max_length=30, unique=True, verbose_name="URL_rs"),
        ),
    ]
