# Generated by Django 4.2.1 on 2025-03-09 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("go", "0003_alter_consorcium_slug_alter_genes_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rs",
            name="link_to_gene",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="go.genes"
            ),
        ),
    ]
