# Generated by Django 4.2.1 on 2025-03-10 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("go", "0004_rs_link_to_gene"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rs",
            name="link_to_gene",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rsset",
                to="go.genes",
            ),
        ),
    ]
