# Generated by Django 4.2.1 on 2025-03-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("go", "0005_alter_rs_link_to_gene"),
    ]

    operations = [
        migrations.AddField(
            model_name="rs",
            name="link_to_pheno",
            field=models.ManyToManyField(
                blank=True, related_name="link_pheno", to="go.phenotype"
            ),
        ),
    ]
