# Generated by Django 4.2.1 on 2025-03-12 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("go", "0007_remove_rs_link_to_pheno_genes_link_to_pheno"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transcripts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tr_name", models.CharField(max_length=40)),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(max_length=30, unique=True, verbose_name="URL_tr"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="genes",
            name="gene_source",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tr_of_gene",
                to="go.transcripts",
            ),
        ),
    ]
