# Generated by Django 4.2.1 on 2025-08-24 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("go", "0008_transcripts_genes_gene_source"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phenotype",
            options={"verbose_name": "Phenotype", "verbose_name_plural": "Phenotypes"},
        ),
        migrations.RenameField(
            model_name="genes",
            old_name="gene_source",
            new_name="transcript",
        ),
    ]
