# Generated by Django 4.2.1 on 2025-08-26 01:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("go", "0009_alter_phenotype_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phenotype",
            name="slug",
        ),
    ]
