# Generated by Django 4.2.1 on 2025-08-26 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("go", "0010_remove_phenotype_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genes",
            name="slug",
        ),
    ]
