# Generated by Django 4.2.1 on 2025-08-26 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("go", "0011_remove_genes_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transcripts",
            name="slug",
        ),
    ]
