# Generated by Django 4.2.1 on 2025-08-26 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("go", "0012_remove_transcripts_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rs",
            name="slug",
        ),
    ]
